# BFR Analysis Data Exploration

In [1]:
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go

## Subject 2 no BFR

### Find SA MVC

In [2]:
# SA muscle
df_mvc = pd.read_csv("output/PB TT Tennis no BFR ALL TRIALs/Subject 2 no BFR/Subject_2_KB__SA_MVC_(EMG_RMS)_(2)_Rep_1.1.hpf-ch_data.csv")

print(df_mvc.columns)

df_mvc.head()

Index(['X [s]', 'Serratus Anterior 2: EMG 2 [V]', 'X [s].1',
       'Serratus Anterior 2: EMG 2->filter (FilterSlidingRMS21) [V]'],
      dtype='object')

,X [s],Serratus Anterior 2: EMG 2 [V],X [s].1,Serratus Anterior 2: EMG 2->filter (FilterSlidingRMS21) [V]
0,0.000000,0.0,0.000000,0.0
1,0.000466,0.0,0.000466,0.0
2,0.000931,0.0,0.000931,0.0
3,0.001397,0.0,0.001397,0.0
4,0.001862,0.0,0.001862,0.0

In [3]:
sa_emg_raw = df_mvc['Serratus Anterior 2: EMG 2 [V]']
print("Max: ", max(sa_emg_raw), "| Min: ", min(sa_emg_raw))
sa_emg_raw_fig = go.Figure(
    data=go.Scatter(
        x=df_mvc["X [s]"], 
        y=df_mvc["Serratus Anterior 2: EMG 2 [V]"], 
        name='Raw data', 
        line=dict(color='blue')
    )
)
sa_emg_raw_fig.update_layout(
    title=dict(
        text='Subject 2 - SA - EMG - Raw data'
    ),
    xaxis=dict(
        title=dict(
            text='Time [S]'
        )
    ),
    yaxis=dict(
        title=dict(
            text='Serratus Anterior 2: EMG 2 [V]'
        )
    ),
)
sa_emg_raw_fig.show()

Max:  0.000323109794408 | Min:  -0.000340566097293

#### RMS Smoothing
> Reference: https://delsys.com/amplitude-analysis-root-mean-square-emg-envelope/

In [4]:
# Smoothing function
def rms_smoothing(df: pd.DataFrame, raw_column: str, smoothed_column: str, window_size: int):
    df[smoothed_column] = np.sqrt(
        df[raw_column].pow(2).rolling(window=window_size).mean()
    )

window_size = 10
rms_smoothing(df_mvc, "Serratus Anterior 2: EMG 2 [V]", "rms_smoothed", window_size)

sa_emg_rms = df_mvc['rms_smoothed']
print("Max: ", np.max(sa_emg_rms), "| Min: ", np.min(sa_emg_rms))
sa_emg_rms_fig = go.Figure(
    data=go.Scatter(
        x=df_mvc["X [s]"], 
        y=df_mvc["rms_smoothed"], 
        name='RMS Smoothed', 
        line=dict(color='red')
    )
)
sa_emg_rms_fig.update_layout(
    title=dict(
        text='Subject 2 - SA - EMG - RMS Smoothed'
    ),
    xaxis=dict(
        title=dict(
            text='Time [S]'
        )
    ),
    yaxis=dict(
        title=dict(
            text='Serratus Anterior 2: EMG 2 RMS Smoothed [V]'
        )
    ),
)
sa_emg_rms_fig.show()

Max:  0.0002986349862422344 | Min:  0.0

In [5]:
sa_emg_fig = go.Figure()

sa_emg_fig.add_trace(
  go.Scatter(
        x=df_mvc["X [s]"], 
        y=df_mvc["Serratus Anterior 2: EMG 2 [V]"], 
        name='Raw data', 
        line=dict(color='blue')
  )
)
sa_emg_fig.add_trace(
    go.Scatter(
        x=df_mvc["X [s]"], 
        y=df_mvc["rms_smoothed"], 
        name='RMS Smoothed', 
        line=dict(color='red')
    )
)
sa_emg_fig.update_layout(
    title=dict(
        text='Subject 2 - SA - EMG - Combined'
    ),
    xaxis=dict(
        title=dict(
            text='Time [S]'
        )
    ),
    yaxis=dict(
        title=dict(
            text='Serratus Anterior 2: EMG 2 Combined [V]'
        )
    ),
)
sa_emg_fig.show()

### Normalization - Pickleball BH - Rep 3 - SA

In [8]:
df_pkbh = pd.read_csv("./output/PB TT Tennis no BFR ALL TRIALs/Subject 2 no BFR/Subject_2_KB_Pickleball_BH_Rep_3_Rep_1.23.hpf-ch_data.csv")
print("SA - Max: ", max(df_pkbh["Serratus Anterior 2: EMG 2 [V]"]), "| Min: ", min(df_pkbh["Serratus Anterior 2: EMG 2 [V]"]))
df_pkbh.head()

SA - Max:  3.541618934832513e-05 | Min:  -2.433814006508328e-05

,X [s],Lower Trapezius 1: EMG 1 [V],X [s].1,Serratus Anterior 2: EMG 2 [V],X [s].2,Anterior Deltoid 3: EMG 3 [V],X [s].3,Bicep 4: EMG 4 [V],X [s].4,ECRB 5: EMG 5 [V],X [s].5,Vastus Medialis 6: EMG 6 [V],X [s].6,Biceps Femoris 7: EMG 7 [V]
0,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0
1,0.000466,0.0,0.000466,0.0,0.000466,0.0,0.000466,0.0,0.000466,0.0,0.000466,0.0,0.000466,0.0
2,0.000931,0.0,0.000931,0.0,0.000931,0.0,0.000931,0.0,0.000931,0.0,0.000931,0.0,0.000931,0.0
3,0.001397,0.0,0.001397,0.0,0.001397,0.0,0.001397,0.0,0.001397,0.0,0.001397,0.0,0.001397,0.0
4,0.001862,0.0,0.001862,0.0,0.001862,0.0,0.001862,0.0,0.001862,0.0,0.001862,0.0,0.001862,0.0

#### Apply the Same RMS Smoothing

In [12]:
# Using the previously defined smoothing function and window size
rms_smoothing(df_pkbh, "Serratus Anterior 2: EMG 2 [V]", "smoothed_sa", window_size)

pkbh_sa_emg_fig = go.Figure()

pkbh_sa_emg_fig.add_trace(
  go.Scatter(
        x=df_pkbh["X [s]"], 
        y=df_pkbh["Serratus Anterior 2: EMG 2 [V]"], 
        name='Raw data', 
        line=dict(color='blue')
  )
)
pkbh_sa_emg_fig.add_trace(
    go.Scatter(
        x=df_pkbh["X [s]"], 
        y=df_pkbh["smoothed_sa"], 
        name='RMS Smoothed', 
        line=dict(color='red')
    )
)
pkbh_sa_emg_fig.update_layout(
    title=dict(
        text='Subject 2 - Pickleball BH - Rep3 - SA - EMG - Combined'
    ),
    xaxis=dict(
        title=dict(
            text='Time [S]'
        )
    ),
    yaxis=dict(
        title=dict(
            text='Serratus Anterior 2: EMG 2 Combined [V]'
        )
    ),
)
pkbh_sa_emg_fig.show()

In [22]:
# previously got subject 2 SA MVC RMS Smoothed Max
mvc_sa_max = np.max(df_mvc["rms_smoothed"])
print("Smoothed MVC Max: ", mvc_sa_max)

# normalized = SA RMS Smoothed / SA MVC Smoothed Max * 100%
df_pkbh["sa_norm_percent"] = df_pkbh["smoothed_sa"].apply(lambda x: np.divide(x, mvc_sa_max)*100)
np.max(df_pkbh["sa_norm_percent"])


pkbh_sa_emg_norm_fig = go.Figure()

pkbh_sa_emg_norm_fig.add_trace(
  go.Scatter(
        x=df_pkbh["X [s]"], 
        y=df_pkbh["sa_norm_percent"], 
        name='Smoothed then Normalized SA EMG', 
        line=dict(color='green')
  )
)
pkbh_sa_emg_norm_fig.update_layout(
    title=dict(
        text='Subject 2 - Pickleball BH - Rep3 - SA - EMG - Smoothed then Normalized'
    ),
    xaxis=dict(
        title=dict(
            text='Time [S]'
        )
    ),
    yaxis=dict(
        title=dict(
            text='Percentage of Smoothed MVC Max'
        )
    ),
)
pkbh_sa_emg_norm_fig.show()

Smoothed MVC Max:  0.0002986349862422344